In [2]:
# Import libraries
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score


# Load iris dataset
df = sns.load_dataset('iris')

# Display first 5 rows
print(df.head())

# Features and target
X = df.iloc[:, 0:4]
y = df.iloc[:, 4]

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)

# Create model
model = GaussianNB()

# Train model
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix")
print(cm)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy:", accuracy)

# Calculate TP, FP, FN, TN for first class
TP = cm[0][0]

FP = cm[:,0].sum() - TP

FN = cm[0,:].sum() - TP

TN = cm.sum() - (TP + FP + FN)

print("\nTP:", TP)
print("FP:", FP)
print("FN:", FN)
print("TN:", TN)

# Precision
precision = TP / (TP + FP)

# Recall
recall = TP / (TP + FN)

# Error Rate
error_rate = 1 - accuracy

print("\nPrecision:", precision)
print("Recall:", recall)
print("Error Rate:", error_rate)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Confusion Matrix
[[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]

Accuracy: 1.0

TP: 15
FP: 0
FN: 0
TN: 23

Precision: 1.0
Recall: 1.0
Error Rate: 0.0
